### ISSUE TITLE
Pod Constantly Crashes And Restarts Silently (In DEBUG)

### ISSUE THREAD

**Issue by Carmezim** [AICoE/prometheus-anomaly-detector#161]
I seem to not be able to get the Tornado serving the endpoints. I am able to train the data and see the results though.

It seems the pod is crashing and restarting each few minutes without any logs in DEBUG mode so it never finishes training and get to start the server.

This is the service
```
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: prometheus-anomaly-detector
  clusterIP: *******
  clusterIPs:
    - ******
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
```

The deployment ports:
```
spec:
      containers:
        - name: prometheus-anomaly-detector
          image: prometheus-anomaly-detector-image
          ports:
            - containerPort: 8080
              protocol: TCP
          hostNetwork: false
```

Running master.
